-- =============================================
-- Seed: cvx_codes
-- A curated starting set of standard CDC CVX (vaccine
-- administered) codes, covering the vaccines most commonly
-- recorded on an immunization history. Idempotent via
-- INSERT IGNORE against the unique `code` constraint.
-- Administrators can add, edit, or retire codes from the
-- CVX Immunization Codes screen; verify against the current
-- published CDC CVX table before relying on this list for
-- production reporting.
-- =============================================

INSERT IGNORE INTO cvx_codes (code, short_description, status, created_at) VALUES
('01', 'diphtheria, tetanus toxoids and pertussis vaccine', 'Active', NOW()),
('02', 'trivalent poliovirus vaccine, live, oral', 'Active', NOW()),
('03', 'measles, mumps and rubella virus vaccine', 'Active', NOW()),
('04', 'measles and rubella virus vaccine', 'Active', NOW()),
('05', 'measles virus vaccine', 'Active', NOW()),
('06', 'rubella virus vaccine', 'Active', NOW()),
('07', 'mumps virus vaccine', 'Active', NOW()),
('08', 'hepatitis B vaccine, pediatric or pediatric/adolescent dosage', 'Active', NOW()),
('09', 'tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use', 'Active', NOW()),
('10', 'poliovirus vaccine, inactivated', 'Active', NOW()),
('11', 'pertussis vaccine', 'Active', NOW()),
('12', 'diphtheria antitoxin', 'Active', NOW()),
('14', 'immune globulin, intramuscular', 'Active', NOW()),
('16', 'influenza virus vaccine, whole virus', 'Active', NOW()),
('17', 'Haemophilus influenzae type b vaccine, unspecified formulation', 'Active', NOW()),
('19', 'Bacillus Calmette-Guerin vaccine', 'Active', NOW()),
('20', 'diphtheria, tetanus toxoids and acellular pertussis vaccine', 'Active', NOW()),
('21', 'varicella virus vaccine', 'Active', NOW()),
('28', 'diphtheria, tetanus toxoids, adsorbed for pediatric use', 'Active', NOW()),
('30', 'hepatitis B immune globulin', 'Active', NOW()),
('32', 'meningococcal polysaccharide vaccine (MPSV4)', 'Active', NOW()),
('33', 'pneumococcal polysaccharide vaccine, 23 valent', 'Active', NOW()),
('35', 'tetanus toxoid, unspecified formulation', 'Active', NOW()),
('37', 'yellow fever vaccine', 'Active', NOW()),
('42', 'hepatitis B vaccine, adolescent/high risk infant formulation', 'Active', NOW()),
('43', 'hepatitis B vaccine, adult dosage', 'Active', NOW()),
('45', 'hepatitis B vaccine, unspecified formulation', 'Active', NOW()),
('46', 'Haemophilus influenzae type b vaccine, PRP-D conjugate', 'Active', NOW()),
('47', 'Haemophilus influenzae type b vaccine, HbOC conjugate', 'Active', NOW()),
('48', 'Haemophilus influenzae type b vaccine, PRP-T conjugate', 'Active', NOW()),
('49', 'Haemophilus influenzae type b vaccine, PRP-OMP conjugate', 'Active', NOW()),
('50', 'diphtheria, tetanus toxoids and acellular pertussis vaccine, Haemophilus influenzae type b conjugate', 'Active', NOW()),
('51', 'Haemophilus influenzae type b conjugate and hepatitis B vaccine', 'Active', NOW()),
('52', 'hepatitis A vaccine, pediatric, unspecified formulation', 'Active', NOW()),
('58', 'zoster vaccine, live', 'Active', NOW()),
('60', 'hepatitis A vaccine, adult dosage', 'Active', NOW()),
('62', 'hepatitis A vaccine, pediatric/adolescent, 3 dose schedule', 'Active', NOW()),
('83', 'hepatitis A vaccine, pediatric/adolescent, 2 dose schedule', 'Active', NOW()),
('88', 'influenza virus vaccine, unspecified formulation', 'Active', NOW()),
('91', 'no vaccine administered', 'Active', NOW()),
('94', 'measles, mumps, rubella, and varicella virus vaccine', 'Active', NOW()),
('100', 'pneumococcal conjugate vaccine, 7 valent', 'Active', NOW()),
('106', 'diphtheria, tetanus toxoids and acellular pertussis vaccine, 5 pertussis antigens', 'Active', NOW()),
('110', 'diphtheria, tetanus toxoids and acellular pertussis vaccine, hepatitis B, and poliovirus vaccine', 'Active', NOW()),
('111', 'influenza virus vaccine, live, attenuated, intranasal', 'Active', NOW()),
('114', 'meningococcal polysaccharide (groups A, C, Y and W-135) diphtheria conjugate vaccine (MCV4O)', 'Active', NOW()),
('115', 'tetanus toxoid, reduced diphtheria toxoid, and acellular pertussis vaccine', 'Active', NOW()),
('116', 'rotavirus, live, pentavalent vaccine', 'Active', NOW()),
('118', 'human papillomavirus vaccine, bivalent', 'Active', NOW()),
('119', 'rotavirus, unspecified formulation', 'Active', NOW()),
('120', 'diphtheria, tetanus toxoids and acellular pertussis, Haemophilus influenzae type b, and poliovirus vaccine', 'Active', NOW()),
('130', 'diphtheria, tetanus toxoids and acellular pertussis, and poliovirus vaccine', 'Active', NOW()),
('133', 'pneumococcal conjugate vaccine, 13 valent', 'Active', NOW()),
('136', 'meningococcal conjugate vaccine (MCV4), unspecified formulation', 'Active', NOW()),
('137', 'human papillomavirus vaccine, quadrivalent', 'Active', NOW()),
('140', 'influenza, seasonal, injectable vaccine', 'Active', NOW()),
('141', 'influenza, seasonal, injectable, preservative free vaccine', 'Active', NOW()),
('144', 'influenza, seasonal, intradermal, preservative free vaccine', 'Active', NOW()),
('148', 'meningococcal conjugate vaccine, serogroups A, C, W, Y', 'Active', NOW()),
('150', 'influenza, high dose seasonal, preservative free vaccine', 'Active', NOW()),
('151', 'influenza, recombinant, injectable, preservative free vaccine', 'Active', NOW()),
('158', 'influenza, injectable, quadrivalent vaccine', 'Active', NOW()),
('161', 'influenza, injectable, quadrivalent, preservative free vaccine', 'Active', NOW()),
('162', 'meningococcal B vaccine, fully recombinant', 'Active', NOW()),
('163', 'meningococcal B vaccine, recombinant, outer membrane vesicle', 'Active', NOW()),
('165', 'human papillomavirus vaccine, 9 valent', 'Active', NOW()),
('187', 'zoster vaccine, recombinant, adjuvanted', 'Active', NOW()),
('208', 'COVID-19, mRNA vaccine', 'Active', NOW()),
('213', 'COVID-19, unspecified formulation', 'Active', NOW());
