CREATE TABLE IF NOT EXISTS `incident_reports` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `incident_number` VARCHAR(30) NOT NULL UNIQUE,
    `incident_date` DATETIME NOT NULL,
    `reported_at` DATETIME NOT NULL,
    `department` VARCHAR(100) NOT NULL,
    `location_details` VARCHAR(255) NULL,
    `event_type` ENUM(
        'Medication Error',
        'Slip / Fall',
        'Equipment Malfunction',
        'Near-Miss',
        'Adverse Drug Reaction',
        'Documentation / Communication',
        'Other'
    ) NOT NULL DEFAULT 'Other',
    `severity_level` ENUM(
        'Near-Miss (No Harm)',
        'Minor (Monitored)',
        'Moderate (Medical Intervention)',
        'Severe / Sentinel Event'
    ) NOT NULL DEFAULT 'Minor (Monitored)',
    `is_anonymous` TINYINT(1) NOT NULL DEFAULT 0,
    `reporter_id` INT NULL,
    `reporter_name` VARCHAR(150) NULL,
    `reporter_role` VARCHAR(100) NULL,
    `patient_id` INT NULL,
    `patient_name` VARCHAR(150) NULL,
    `patient_mrn` VARCHAR(50) NULL,
    `summary` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    `immediate_action_taken` TEXT NOT NULL,
    `contributing_factors` TEXT NULL,
    `status` ENUM(
        'Reported',
        'Under Investigation',
        'Root Cause Analysis',
        'Corrective Action Planned',
        'Closed'
    ) NOT NULL DEFAULT 'Reported',
    `investigator_id` INT NULL,
    `investigator_name` VARCHAR(150) NULL,
    `root_cause_analysis` TEXT NULL,
    `corrective_preventive_action` TEXT NULL,
    `resolution_notes` TEXT NULL,
    `closed_at` DATETIME NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_incident_date` (`incident_date`),
    INDEX `idx_department` (`department`),
    INDEX `idx_event_type` (`event_type`),
    INDEX `idx_severity` (`severity_level`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;