-- 102_hai_ssi_infections.sql
-- JCAHO: Hospital-Acquired Infection (HAI) & Surgical Site Infection (SSI) Report Schema

CREATE TABLE IF NOT EXISTS `hai_ssi_infections` (
    `id`                            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `tracking_number`               VARCHAR(30)   NOT NULL UNIQUE,
    `report_date`                   DATETIME      NOT NULL,
    `infection_type`                ENUM('SSI','CLABSI','CAUTI','VAP','MRSA','CDI','Other HAI') NOT NULL DEFAULT 'SSI',
    `infection_category`            ENUM('Superficial Incisional','Deep Incisional','Organ/Space','Primary Bloodstream','Urinary Tract','Pneumonia','Skin/Soft Tissue','Other') NOT NULL DEFAULT 'Superficial Incisional',
    `procedure_type`                VARCHAR(255)  DEFAULT NULL,
    `surgery_date`                  DATE          DEFAULT NULL,
    `onset_date`                    DATE          NOT NULL,
    `days_post_op`                  INT UNSIGNED  DEFAULT NULL,
    `department`                    VARCHAR(150)  NOT NULL,
    `ward_bed`                      VARCHAR(100)  DEFAULT NULL,
    `patient_id`                    INT UNSIGNED  DEFAULT NULL,
    `patient_name`                  VARCHAR(200)  DEFAULT NULL,
    `patient_mrn`                   VARCHAR(80)   DEFAULT NULL,
    `patient_age`                   INT UNSIGNED  DEFAULT NULL,
    `patient_risk_factors`          TEXT          DEFAULT NULL,
    `surgeon_attending`             VARCHAR(200)  DEFAULT NULL,
    `identified_by`                 VARCHAR(200)  NOT NULL,
    `identified_by_role`            VARCHAR(150)  DEFAULT NULL,
    `pathogen_isolated`             VARCHAR(255)  DEFAULT NULL,
    `antibiotic_resistance`         VARCHAR(255)  DEFAULT NULL,
    `antibiotic_prophylaxis_given`  TINYINT(1)    NOT NULL DEFAULT 0,
    `prophylaxis_timing_correct`    TINYINT(1)    NOT NULL DEFAULT 0,
    `device_associated`             TINYINT(1)    NOT NULL DEFAULT 0,
    `device_type`                   VARCHAR(150)  DEFAULT NULL,
    `device_days`                   INT UNSIGNED  DEFAULT NULL,
    `severity`                      ENUM('Mild','Moderate','Severe','Critical') NOT NULL DEFAULT 'Moderate',
    `outcome`                       ENUM('Resolved','Ongoing','Transferred','Deceased','Discharged with Infection') DEFAULT 'Ongoing',
    `treatment`                     TEXT          DEFAULT NULL,
    `isolation_precautions`         VARCHAR(255)  DEFAULT NULL,
    `bundle_compliance`             TINYINT(1)    NOT NULL DEFAULT 0,
    `reported_to_cdc`               TINYINT(1)    NOT NULL DEFAULT 0,
    `root_cause`                    TEXT          DEFAULT NULL,
    `corrective_action`             TEXT          DEFAULT NULL,
    `status`                        ENUM('Active','Under Investigation','Resolved','Reported','Closed') NOT NULL DEFAULT 'Active',
    `notes`                         TEXT          DEFAULT NULL,
    `created_at`                    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`                    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_report_date    (`report_date`),
    INDEX idx_infection_type (`infection_type`),
    INDEX idx_department     (`department`),
    INDEX idx_status         (`status`),
    INDEX idx_onset_date     (`onset_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
