-- 103_readmission_mortality.sql
-- JCAHO / CMS: 30-Day Readmission & Hospital Mortality Report Schema

CREATE TABLE IF NOT EXISTS `readmission_mortality_records` (
    `id`                                    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `record_number`                         VARCHAR(30)   NOT NULL UNIQUE,
    `index_admission_date`                  DATE          NOT NULL,
    `index_discharge_date`                  DATE          NOT NULL,
    `length_of_stay`                        INT UNSIGNED  NOT NULL DEFAULT 1,
    `department`                            VARCHAR(150)  NOT NULL,
    `ward_bed`                              VARCHAR(100)  DEFAULT NULL,
    `patient_id`                            INT UNSIGNED  DEFAULT NULL,
    `patient_name`                          VARCHAR(200)  NOT NULL,
    `patient_mrn`                           VARCHAR(80)   NOT NULL,
    `patient_age`                           INT UNSIGNED  NOT NULL,
    `gender`                                ENUM('Male', 'Female', 'Other') NOT NULL DEFAULT 'Male',
    `primary_diagnosis`                     VARCHAR(255)  NOT NULL,
    `icd10_code`                            VARCHAR(30)   DEFAULT NULL,
    `attending_physician`                   VARCHAR(200)  NOT NULL,
    `discharge_disposition`                 ENUM('Home', 'Home with Home Health', 'Skilled Nursing Facility (SNF)', 'Rehabilitation Facility', 'Long-term Acute Care (LTAC)', 'Hospice', 'Expired', 'AMA') NOT NULL DEFAULT 'Home',
    `readmission_status`                    ENUM('No Readmission', 'Planned Readmission', 'Unplanned Readmission (Within 30 Days)', 'Readmission (>30 Days)') NOT NULL DEFAULT 'No Readmission',
    `readmission_date`                      DATE          DEFAULT NULL,
    `days_to_readmission`                   INT UNSIGNED  DEFAULT NULL,
    `readmission_diagnosis`                 VARCHAR(255)  DEFAULT NULL,
    `readmission_department`                VARCHAR(150)  DEFAULT NULL,
    `readmission_preventable`               TINYINT(1)    NOT NULL DEFAULT 0,
    `mortality_status`                      ENUM('Alive', 'Inpatient Mortality', '30-Day Post-Discharge Mortality') NOT NULL DEFAULT 'Alive',
    `mortality_date`                        DATE          DEFAULT NULL,
    `days_to_mortality`                     INT UNSIGNED  DEFAULT NULL,
    `cause_of_death`                        VARCHAR(255)  DEFAULT NULL,
    `post_discharge_followup_call`          TINYINT(1)    NOT NULL DEFAULT 0,
    `followup_appointment_scheduled`        TINYINT(1)    NOT NULL DEFAULT 0,
    `medication_reconciliation_completed`   TINYINT(1)    NOT NULL DEFAULT 0,
    `risk_score`                            ENUM('Low', 'Medium', 'High', 'Very High') NOT NULL DEFAULT 'Medium',
    `root_cause_analysis`                   TEXT          DEFAULT NULL,
    `intervention_plan`                     TEXT          DEFAULT NULL,
    `status`                                ENUM('Discharged', 'Under 30-Day Surveillance', 'Readmitted', 'Closed - 30d Completed', 'Mortality Review') NOT NULL DEFAULT 'Under 30-Day Surveillance',
    `notes`                                 TEXT          DEFAULT NULL,
    `created_at`                            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`                            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_index_discharge_date (`index_discharge_date`),
    INDEX idx_readmission_status   (`readmission_status`),
    INDEX idx_mortality_status     (`mortality_status`),
    INDEX idx_department           (`department`),
    INDEX idx_primary_diagnosis    (`primary_diagnosis`),
    INDEX idx_status               (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
