-- =========================================================
-- OPERATING ROOM (OR) MANAGEMENT MODULE SCHEMA & SEED
-- =========================================================

CREATE TABLE IF NOT EXISTS `or_suites` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `suite_code` VARCHAR(30) NOT NULL UNIQUE,
    `suite_name` VARCHAR(100) NOT NULL,
    `suite_type` ENUM('Major OR', 'Minor OR', 'Endoscopy', 'Hybrid OR', 'Cath Lab') NOT NULL DEFAULT 'Major OR',
    `floor_location` VARCHAR(100) NOT NULL DEFAULT '3rd Floor - Surgical Tower',
    `status` ENUM('Available', 'In Surgery', 'Cleaning / Turnover', 'Maintenance', 'Blocked') NOT NULL DEFAULT 'Available',
    `current_case_id` INT UNSIGNED NULL,
    `turnover_started_at` DATETIME NULL,
    `equipment_spec` TEXT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_suite_status` (`status`),
    INDEX `idx_suite_type` (`suite_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `or_surgical_cases` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `case_number` VARCHAR(50) NOT NULL UNIQUE,
    `patient_id` INT UNSIGNED NULL,
    `patient_name` VARCHAR(150) NOT NULL,
    `patient_mrn` VARCHAR(50) NULL,
    `patient_age` INT NULL,
    `gender` VARCHAR(20) NULL,
    `or_suite_id` INT UNSIGNED NOT NULL,
    `or_suite_name` VARCHAR(100) NOT NULL,
    `scheduled_date` DATE NOT NULL,
    `scheduled_start_time` TIME NOT NULL,
    `scheduled_end_time` TIME NOT NULL,
    `estimated_duration_minutes` INT NOT NULL DEFAULT 60,
    `actual_in_room_time` DATETIME NULL,
    `actual_incision_time` DATETIME NULL,
    `actual_closing_time` DATETIME NULL,
    `actual_out_room_time` DATETIME NULL,
    `turnover_duration_minutes` INT NULL,
    `surgical_specialty` VARCHAR(100) NOT NULL,
    `procedure_name` VARCHAR(255) NOT NULL,
    `preop_diagnosis` VARCHAR(255) NULL,
    `postop_diagnosis` VARCHAR(255) NULL,
    `lead_surgeon` VARCHAR(150) NOT NULL,
    `assistant_surgeon` VARCHAR(150) NULL,
    `anesthesiologist` VARCHAR(150) NOT NULL,
    `scrub_nurse` VARCHAR(150) NULL,
    `circulating_nurse` VARCHAR(150) NULL,
    `anesthesia_type` VARCHAR(80) NOT NULL DEFAULT 'General',
    `case_priority` ENUM('Elective', 'Urgent', 'Emergency / STAT') NOT NULL DEFAULT 'Elective',
    `perioperative_stage` ENUM('Scheduled', 'Pre-Op Holding', 'In Room / Induction', 'Incision / In Progress', 'Closing / Extubation', 'In PACU', 'Transferred / Discharged', 'Cancelled') NOT NULL DEFAULT 'Scheduled',
    `preop_cleared` TINYINT(1) NOT NULL DEFAULT 1,
    `consent_signed` TINYINT(1) NOT NULL DEFAULT 1,
    `blood_reserved` TINYINT(1) NOT NULL DEFAULT 0,
    `blood_units_reserved` INT NOT NULL DEFAULT 0,
    `implants_required` TINYINT(1) NOT NULL DEFAULT 0,
    `implant_details` TEXT NULL,
    `estimated_blood_loss_ml` INT NULL,
    `specimens_sent` VARCHAR(255) NULL,
    `pacu_bed_no` VARCHAR(50) NULL,
    `pacu_aldrete_score` INT NULL,
    `pacu_discharge_time` DATETIME NULL,
    `postop_disposition` VARCHAR(100) NULL DEFAULT 'PACU',
    `safety_checklist_id` INT UNSIGNED NULL,
    `delay_reason` VARCHAR(255) NULL,
    `cancellation_reason` VARCHAR(255) NULL,
    `notes` TEXT NULL,
    `created_by` INT UNSIGNED NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_or_date` (`scheduled_date`),
    INDEX `idx_or_suite` (`or_suite_id`),
    INDEX `idx_or_stage` (`perioperative_stage`),
    INDEX `idx_or_priority` (`case_priority`),
    INDEX `idx_or_patient` (`patient_id`),
    INDEX `idx_or_surgeon` (`lead_surgeon`),
    CONSTRAINT `fk_or_cases_suite` FOREIGN KEY (`or_suite_id`) REFERENCES `or_suites` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
