-- =============================================
-- Table: patient_reminders
-- One row per (practice_rule, patient) match generated by running
-- "Process Reminders" -- the operational counterpart to practice_rules
-- (type = 'Patient Reminder'): the rule defines WHO/WHAT should be
-- reminded, this table records that a specific patient IS currently
-- due, and tracks whether/when each contact channel was notified.
-- =============================================

CREATE TABLE IF NOT EXISTS patient_reminders (

    id INT NOT NULL AUTO_INCREMENT,

    practice_rule_id INT NOT NULL,

    patient_id INT NOT NULL,

    item_label VARCHAR(255) NOT NULL,

    due_status VARCHAR(20) NOT NULL DEFAULT 'due',

    date_created DATETIME NOT NULL,

    date_sent DATETIME NULL,

    voice_sent TINYINT(1) NOT NULL DEFAULT 0,

    email_sent TINYINT(1) NOT NULL DEFAULT 0,

    sms_sent TINYINT(1) NOT NULL DEFAULT 0,

    mail_sent TINYINT(1) NOT NULL DEFAULT 0,

    created_at DATETIME NULL,

    created_by INT NULL,

    updated_at DATETIME NULL,

    updated_by INT NULL,

    deleted_at DATETIME NULL,

    deleted_by INT NULL,

    PRIMARY KEY (id),

    CONSTRAINT uq_patient_reminders_rule_patient
        UNIQUE (practice_rule_id, patient_id),

    INDEX idx_patient_reminders_patient (patient_id),

    INDEX idx_patient_reminders_due_status (due_status),

    INDEX idx_patient_reminders_created_by (created_by),

    INDEX idx_patient_reminders_updated_by (updated_by),

    INDEX idx_patient_reminders_deleted_by (deleted_by),

    CONSTRAINT fk_patient_reminders_rule
        FOREIGN KEY (practice_rule_id)
        REFERENCES practice_rules(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_patient_reminders_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE

) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
