-- ============================================================================
-- Migration 203: HIPAA Business Associate Agreement (BAA) & Vendor Governance
-- Statutory Citations: 45 CFR § 164.502(e), § 164.504(e), and § 164.308(b)(1)
-- ============================================================================

CREATE TABLE IF NOT EXISTS `hipaa_business_associates` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `vendor_name` VARCHAR(255) NOT NULL,
    `vendor_category` ENUM(
        'cloud_hosting',
        'communications',
        'email_relay',
        'laboratory_interface',
        'billing_clearinghouse',
        'transcription_ai',
        'it_managed_services',
        'document_destruction',
        'legal_audit_consulting',
        'other'
    ) NOT NULL DEFAULT 'other',
    `service_description` TEXT NOT NULL,
    `phi_data_types_handled` VARCHAR(255) NOT NULL,
    `primary_contact_name` VARCHAR(150) NULL,
    `primary_contact_email` VARCHAR(150) NULL,
    `primary_contact_phone` VARCHAR(50) NULL,
    `vendor_address` VARCHAR(255) NULL,
    `has_signed_baa` TINYINT(1) NOT NULL DEFAULT 0,
    `baa_execution_date` DATE NULL,
    `baa_expiration_date` DATE NULL,
    `last_compliance_audit_date` DATE NULL,
    `next_review_deadline` DATE NULL,
    `baa_document_filename` VARCHAR(255) NULL,
    `baa_document_path` VARCHAR(255) NULL,
    `baa_status` ENUM('active', 'expiring_soon', 'expired', 'missing_baa') NOT NULL DEFAULT 'missing_baa',
    `subcontractor_handling_phi` TINYINT(1) NOT NULL DEFAULT 0,
    `soc2_or_hitrust_certified` TINYINT(1) NOT NULL DEFAULT 0,
    `breach_notification_sla_hours` INT UNSIGNED NOT NULL DEFAULT 72,
    `notes` TEXT NULL,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `created_by` INT UNSIGNED NULL,
    `updated_by` INT UNSIGNED NULL,
    `deleted_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_baa_category` (`vendor_category`),
    INDEX `idx_baa_status` (`baa_status`),
    INDEX `idx_baa_expiration` (`baa_expiration_date`),
    INDEX `idx_baa_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Seed baseline healthcare Business Associates
-- ============================================================================
INSERT INTO `hipaa_business_associates` (
    `vendor_name`,
    `vendor_category`,
    `service_description`,
    `phi_data_types_handled`,
    `primary_contact_name`,
    `primary_contact_email`,
    `primary_contact_phone`,
    `vendor_address`,
    `has_signed_baa`,
    `baa_execution_date`,
    `baa_expiration_date`,
    `last_compliance_audit_date`,
    `next_review_deadline`,
    `baa_document_filename`,
    `baa_status`,
    `subcontractor_handling_phi`,
    `soc2_or_hitrust_certified`,
    `breach_notification_sla_hours`,
    `notes`
) VALUES 
(
    'Amazon Web Services (AWS)',
    'cloud_hosting',
    'Dedicated HIPAA-compliant VPC cloud hosting, RDS Aurora database replication, and S3 encrypted backup object storage.',
    'Demographics, Clinical Records, Encrypted Backups, SOAP Notes',
    'AWS Healthcare Enterprise Support',
    'aws-hipaa-compliance@amazon.com',
    '1-800-AWS-SUPPORT',
    '410 Terry Ave N, Seattle, WA 98109',
    1,
    '2024-01-15',
    '2027-01-15',
    '2026-01-10',
    '2027-01-10',
    'AWS_Business_Associate_Addendum_Executed.pdf',
    'active',
    1,
    1,
    24,
    'AWS Artifact Enterprise BAA executed covering RDS, S3, KMS, and CloudWatch audit logging.'
),
(
    'Twilio Inc.',
    'communications',
    'HIPAA-compliant SMS appointment reminders, automated notification dispatch, and 2FA authentication SMS verification.',
    'Patient Name, Appointment Time, Phone Number, 2FA OTPs',
    'Twilio Healthcare Privacy Desk',
    'privacy-hipaa@twilio.com',
    '1-844-818-9454',
    '101 Spear Street, 1st Floor, San Francisco, CA 94105',
    1,
    '2024-06-01',
    '2027-06-01',
    '2026-05-15',
    '2027-05-15',
    'Twilio_Signed_BAA_v2024.pdf',
    'active',
    0,
    1,
    48,
    'HIPAA BAA signed covering Twilio Programmable Messaging and Verify APIs.'
),
(
    'Quest Diagnostics Inc.',
    'laboratory_interface',
    'HL7 electronic laboratory order transmission and diagnostic test result ingestion interface.',
    'Patient Demographics, Lab Orders, Blood Chemistry, Diagnostic Results',
    'Quest Client Integration Support',
    'hipaa-integrations@questdiagnostics.com',
    '1-866-697-8378',
    '500 Plaza Drive, Secaucus, NJ 07094',
    1,
    '2023-09-01',
    '2026-09-01',
    '2025-08-20',
    '2026-08-20',
    'Quest_Diagnostics_National_BAA.pdf',
    'expiring_soon',
    1,
    1,
    24,
    'Annual review pending. Requires 2026-2029 renewal countersignature.'
),
(
    'Change Healthcare / Optum',
    'billing_clearinghouse',
    'EDI 837P insurance claim submission, EDI 835 remittance processing, and real-time eligibility inquiry (270/271).',
    'Demographics, Insurance ID, ICD-10 Diagnosis, CPT Procedure Codes, Billing Balances',
    'Optum Clearinghouse Compliance',
    'clearinghouse-compliance@optum.com',
    '1-800-845-6592',
    '11000 Optum Circle, Eden Prairie, MN 55344',
    1,
    '2024-03-10',
    '2027-03-10',
    '2026-02-15',
    '2027-02-15',
    'ChangeHealthcare_Executed_BAA_2024.pdf',
    'active',
    1,
    1,
    24,
    'Enhanced third-party cybersecurity and SOC2 Type II attestations on file.'
),
(
    'Local Medical Transcription Services LLC',
    'transcription_ai',
    'Dictated audio transcription for physician clinical SOAP narratives and consultative summaries.',
    'Clinical Audio Recordings, Physician Dictation, Detailed Patient Diagnoses',
    'Sarah Jenkins (Managing Director)',
    'sjenkins@localmedtranscribe.com',
    '555-019-8234',
    '240 Main St, Suite 3B, Springfield, IL',
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'missing_baa',
    0,
    0,
    72,
    'AUDIT WARNING: Vendor handles sensitive clinical audio but executed BAA is missing from compliance files!'
);
